### ISSUE TITLE
use of tempfile.mkdtemp()

### ISSUE THREAD

**Issue by raihaan** [CobraLab/MAGeTbrain#21]
From the documentation I found, I believe it is the responsibility of the user to delete any directories/files created using tempfile.  
https://docs.python.org/3/library/tempfile.html

I can't find anything in the mb pipeline that removes the temp directories generated - am I missing it or do they get automatically removed on scinet through some other process?

**Comment by gdevenyi** [comment]
From what I've read, SGE and PBS both monitor /tmp creation and cleanup when jobs finish automagically.

**Comment by pipitone** [comment]
I'd love to see a reference for that. :-)

**Comment by vfonov** [comment]
That works only if you use TMPDIR environment variable: 
sge creates a temporary directory - assigns it to that variable and deletes it when the job is done. 
it's described in http://gridscheduler.sourceforge.net/htmlman/htmlman5/queue_conf.html

**Comment by gdevenyi** [comment]
Thanks @vfonov that's exactly what i was talking about.

@pipitone with regards to scinet, the systems are actually diskless, so /tmp is definitely ram-backed, although we should be pointing at /dev/shm I think. If our files aren't too big....
