### ISSUE TITLE
Investigate mincANTS -a

### ISSUE THREAD

**Issue by raihaan** [CobraLab/MAGeTbrain#22]
current setup in mb_register goes linear, resample, feed output of resample into nonlinear

investigate use of mincANTS -a, which potentially removes need to compute and save the intermediate/resampled .mnc file.

From mincANTS -help:

-a, --initial-affine: 
              use the input file as the initial affine parameter

**Comment by pipitone** [comment]
So the reason to separate the stages and include a resampling Is to keep memory use low. That is, when I was experimenting with ANTS, if I registered two images that differed in resolution (eg. High res atlas and ADNI image) ANTS would sometimes use piles of memory -- perhaps resampling both images into a higher gridding common to both images?

Resampling into the same space after a linear registration avoids this I think. 

So, when you do experiment with using -a be sure to try it with different resolutions.

**Comment by gdevenyi** [comment]
mincANTS no longer used.
