### ISSUE TITLE
Investigate /dev/shm as temporary file storage location

### ISSUE THREAD

**Issue by gdevenyi** [CobraLab/MAGeTbrain#27]
/dev/shm is a ram-backed temporary file system, which can be significantly faster than /tmp which is disk backed. Investigate changing storage of temporary files to /dev/shm.

Drawback of this is that files in /dev/shm take up RAM so OOM is a possibility.

**Comment by pipitone** [comment]
Definitely recommended if doing lots of IO with small files on scinet.  :-D

**Comment by gdevenyi** [comment]
Turns out we're already using ramfs as on scinet the entire system FS is in ram.
