### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by raihaan** [CobraLab/MAGeTbrain#28]
Investigate a method to limit the number of dependencies, whether this means grouping more stages together or requiring batched runs.

Especially problematic in large batches running morpho, where one vote job submitted per subject, and each morpho job lists all voting jobs (=number of subjects) as dependencies - high number of dependencies causes problems for scinet scheduler

**Comment by gdevenyi** [comment]
I think once we have morpho running, we need to take a step back and determine what is the core magetbrain algoritm and what is post-processing.

I suspect that some of the things morpo does is "post processing" which should be properly moved to a separate tool.

**Comment by pipitone** [comment]
Alternatively, rather than submitting jobs for a stage separately, use one array job. Then dependencies are easy.

**Comment by gdevenyi** [comment]
Cleaned up with new qbatch
