### ISSUE TITLE
simplified branch depends on minc-stuffs for voxel_vote but doesn't tell you that

### ISSUE THREAD

**Issue by pipitone** [CobraLab/MAGeTbrain#37]
@gdevenyi, as of your last commit (a1c18ad), you've moved to using the `voxel_vote` script from `minc-stuffs` but this dependency isn't listed anywhere. How come the switch to using minc-stuff's voxel-vote and not keeping it packaged with magetbrain?

**Comment by gdevenyi** [comment]
I notified all users on scinet via our announce list

**Comment by gdevenyi** [comment]
The reason is our voxel_vote was broken compared to the much newer minc-stuffs version, which properly supports minc v2

**Comment by gdevenyi** [comment]
Technically, there's no dependencies listed anywhere in the magetbrain readme...

**Comment by pipitone** [comment]
True. :-) Perhaps the issue should be that dependencies aren't listed in the README. I'll send you a PR.

**Comment by pipitone** [comment]
Just looking at [minc-stuffs/voxel-vote](https://github.com/Mouse-Imaging-Centre/minc-stuffs/blob/master/python/voxel_vote), and it looks identical in terms of what libraries it imports, and how it computes the mode. The only major difference in the set up is using `ushort` dtype, and setting `labels=true` when handling volumes. 

Is the minc version 1 vs version 2 handling fix something that happened in `pyminc` itself?

**Comment by gdevenyi** [comment]
I believe it's a combination of the additional settings you noted and updates to pyminc.
