### ISSUE TITLE
metric in mb_register linear register

### ISSUE THREAD

**Issue by sunnyxiao7** [CobraLab/MAGeTbrain#39]
should the metric in mb_register linear register be CC[$target, $atlas,1,4], rather than [$atlas, $target]?

**Comment by gdevenyi** [comment]
Hi @sunnyxiao7,

ANTs and MINC use opposite definitions of what a "transform" does. Since we use ANTs to compute our transform but minc tools to apply them, we need to reverse the order the transformation is calculated.

As such, this is "not a bug".

Thanks for your interest in MAGeTbrain :)
