### ISSUE TITLE
Trailing Comma in label_vols interferes with R's read.csv

### ISSUE THREAD

**Issue by cfhammill** [CobraLab/MAGeTbrain#42]
The trailing comma produced by label_vols interferes with R's `read.csv`. R (3.2.3 and probably earlier versions as well) interprets the trailing comma as an empty field and the file names get treated as rownames.

**Comment by gdevenyi** [comment]
file names being treated as row names depend upon setting up read.csv to ignore, set  row.names = NULL

To deal with the empty field just overwrite with `<-NULL`

I know this script does this. I haven't had time to figure out why. The long term plan is to replace it with the a call to anatGetAll from RMINC once I finish making the CSV files.

PRs to fix this welcome.
