### ISSUE TITLE
Feature Request: Allow alternative module specification in qbatch

### ISSUE THREAD

**Issue by cfhammill** [CobraLab/MAGeTbrain#44]
I'm starting to use MAGeTBrain on the SickKids PBS cluster, I had to edit qbatch to use our modules. Would it be possible to add a way to specify alternative modules?

**Comment by gdevenyi** [comment]
Hi,

Not sure what you're asking for here. qbatch doesn't "use" any modules.

**Comment by cfhammill** [comment]
https://github.com/CobraLab/MAGeTbrain/blob/simplified/bin/qbatch#L132

If the scheduler is a PBS system, qbatch adds the mchakrav scinet modules to the submit scripts. I overwrote these to get it to work on our system but would prefer not to be out of sync with the main repository

**Comment by gdevenyi** [comment]
Fixed and gone. Relies on environment mb is running in now.
