### ISSUE TITLE
parallel: Error: Command line too long (160329 >= 131049) at input 0: voxel_vote

### ISSUE THREAD

**Issue by jadenecke** [CobraLab/MAGeTbrain#56]
Disclaimer: I think this problem is already on my side to fix, but I still wanted to let you know:
The voxel_vote call runs into problem with its character length being to long. The problem stems from a combination of file name length and a high number of atlases and templates. E.g. in my case, voxel_vote calls 900 .mnc files. Therefore, if the full /path/to/file name has more then ~ 145 character (131049 / 900), it exceeds the maximum command line length of 131049 character.

I also piped the command output into a log file: 
`mb run vote -s +++masked-filename+++ -q parallel -j 1 -n &> log.txt`
Lo and behold, the file is ~160500 character long:

```
parallel
-j1
	voxel_vote
/path/to/atlas1_template1_subject1.mnc
/path/to/atlas1_template2_subject1.mnc
/path/to/atlas1_template3_subject1.mnc
...
/path/to/atlas30_template30_subject1.mnc
```

I would not know a way to circumvent this, other than reducing path/file name length or reduce the number of templates. 

Full error log:
```
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	30 atlases found. Use an odd number for best results
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	30 templates found. Use an odd number for best results
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	30 atlases, 30 templates, 1 subjects found
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	parallel: Error: Command line too long (160329 >= 131049) at input 0: voxel_vote /+++masked+++/...
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	Traceback (most recent call last):
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	  File "/+++/+++masked+++/+++/MAGeTbrain/bin/mb", line 792, in <module>
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	    main()
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	  File "/+++/+++masked+++/+++/MAGeTbrain/bin/mb", line 220, in main
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	    options.func(options)
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	  File "/+++/+++masked+++/+++/MAGeTbrain/bin/mb", line 329, in command_run
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	    p.run()
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	  File "/+++/+++masked+++/+++/MAGeTbrain/bin/mb", line 608, in run
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	    self.queue.run(stages=self._get_stage_order())
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	  File "/+++/+++masked+++/+++/MAGeTbrain/bin/mb", line 508, in run
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	    self.parallel(self.commands[stage])
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	  File "/+++/+++masked+++/+++/MAGeTbrain/bin/mb", line 514, in parallel
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	    self.execute(command, input='\n'.join(commands))
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	  File "/+++/+++masked+++/+++/MAGeTbrain/bin/mb", line 492, in execute
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	    raise Exception("Returns %i :: %s" % (proc.returncode, command))
/+++/+++masked+++/+++/MAGeTbrain/bin/mb run vote -s +++masked-filename+++ -j 3 -q parallel	Exception: Returns 255 :: parallel -j3 
```

**Comment by gdevenyi** [comment]
WOW. 30 atlases and 30 templates. That is far far far outside the design spec of MAGeTbrain's original conception. We run with 5 atlases and 21-25 templates (as per the original paper). This will be the origin of the *huge* number of files.

I have a python+SimpleITK (pip install simpleitk) voting script available at https://github.com/CoBrALab/antsRegistration-MAGeT/blob/master/bin/simpleitk_weighted_vote.py (weights are equal by default, making it Majority Vote).

If you're reasonably python-savvy, you could adjust it to read in a text file for the list of inputs (and create the text file based on your logging above. I can take a look at it on the weekend perhaps to hack it together

**Comment by jadenecke** [comment]
Thank you for your input and kind offer to help. I circumvented the problem by renaming the files (as they had quite a bit of unnecessary text in them). I think your last suggestion would be the best to implement, though i don't see the necessity right now, as I appear to be the only one with this problem (with an unintended use case on top).
