### ISSUE TITLE
error while running Magetbrain using Docker

### ISSUE THREAD

**Issue by neer86upadhyay** [CobraLab/MAGeTbrain#57]
Dear Gabriel, 
We are trying to segment the Habenula from the T1 images using the Magetbrain. we already pulled the docker container and arranged the data as per instructions.  we are getting the following error when ran the mb run.

Please have a look and help us in sorting this out. 

 mb_register_labelmask_antsReg_allANTs /home/fmrilab/Dokumente/Studien/RUNSTUD/MagetBrain/input/atlases/brains/brain1_t1.mnc /home/fmrilab/Dokumente/Studien/RUNSTUD/MagetBrain/input/templates/brains/04LIUS27_T6_T1w_biascorr_brain.mnc /home/fmrilab/Dokumente/Studien/RUNSTUD/MagetBrain/output/registrations/brain1_t1/04LIUS27_T6_T1w_biascorr_brain/nl.xfm    ValueError: could not convert string to float: ' cant read /home/fmrilab/Dokumente/Studien/RUNSTUD/MagetBrain/input/atlases/labels/brain1_t1_labels.mnc'
mb_register_labelmask_antsReg_allANTs /home/fmrilab/Dokumente/Studien/RUNSTUD/MagetBrain/input/atlases/brains/brain1_t1.mnc /home/fmrilab/Dokumente/Studien/RUNSTUD/MagetBrain/input/templates/brains/04LIUS27_T6_T1w_biascorr_brain.mnc /home/fmrilab/Dokumente/Studien/RUNSTUD/MagetBrain/output/registrations/brain1_t1/04LIUS27_T6_T1w_biascorr_brain/nl.xfm    + moving_minimum_resolution=
qbatch: error: local run call returned error code 101
Traceback (most recent call last):
  File "/opt/MAGeTbrain/bin/mb", line 792, in <module>
    main()
  File "/opt/MAGeTbrain/bin/mb", line 220, in main
    options.func(options)
  File "/opt/MAGeTbrain/bin/mb", line 329, in command_run
    p.run()
  File "/opt/MAGeTbrain/bin/mb", line 608, in run
    self.queue.run(stages=self._get_stage_order())
  File "/opt/MAGeTbrain/bin/mb", line 539, in run
    processors=processors)
  File "/opt/MAGeTbrain/bin/mb", line 559, in qbatch
    opt_afterok, opt_batchsize, opt_walltime), input='\n'.join(commands))
  File "/opt/MAGeTbrain/bin/mb", line 492, in execute
    raise Exception("Returns %i :: %s" % (proc.returncode, command))
Exception: Returns 1 :: qbatch --jobname mb_templatelib_2021-05-03T15-21-04 --depend NONE* --chunksize 8 --walltime 6:00:00 -

Best regards, 
Neeraj

**Comment by gdevenyi** [comment]
Please report issues with the docker container on the appropriate github. In addition, please provide a complete description of all steps taken when you request assistance.
