### ISSUE TITLE
Question regarding data preparation

### ISSUE THREAD

**Issue by mdaamen** [CobraLab/MAGeTbrain#60]
Hello,

I have a general question related to MR data preparation: 

Does MAGetbrain make demands regarding (a) the positioning of the origin and (b) (AC-PC) orientation of the MR images?

Since we have quite a few peculiar results for the habenula segmentation pipeline, I'm looking for possible technical reasons. Coming from SPM that would be my first guess. I could not find any explicit comments on these technical aspects, my apologies if I overlooked it.

Best wishes,

Marcel

**Comment by gdevenyi** [comment]
Hi,

The pipeline does not require any particular input orientation, "native space" is just fine. However... it does require proper RAS coordinate system, and last I checked SPM does not write out spec-conformant NIFTI files, so if you're coming from there beware getting that right.

**Comment by mdaamen** [comment]
Hi,

thank you. 

We were aware of this and did convert the images to RAS before processing. I was just checking possible error sources I knew from other software, and at least in SPM, these two factors are "usual suspects".

Best wishes,

Marcel
